import type { Metadata } from "next";
// eslint-disable-next-line camelcase
import { Poppins, Roboto, Bodoni_Moda } from "next/font/google";
import "./globals.css";
import React from "react";

import Navbar from "@/components/shared/Navbar";

const poppins = Poppins({
    subsets: ["latin"],
    variable: "--font-poppins",
    weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

const roboto = Roboto({
    subsets: ["latin"],
    variable: "--font-roboto",
    weight: ["100", "300", "400", "500", "700", "900"],
});

const bodoniModa = Bodoni_Moda({
    subsets: ["latin"],
    variable: "--font-bodoni-moda",
    weight: ["400", "500", "600", "700"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body
                className={`${poppins.variable} ${roboto.variable} ${bodoniModa.variable} antialiased`}>
                <header>
                    <Navbar />
                </header>

                {children}
            </body>
        </html>
    );
}
